### ISSUE TITLE
where is the package available?

### ISSUE THREAD

**Issue by gsgou** [Axemasta/Maui.TouchEffect#1]
probably meantime i am supposed to use a ProjectReference

**Comment by Axemasta** [comment]
Hey @gsgou I haven't made the package available anywhere since I was hoping the MCT guys would merge their feature branch with net8 + everyone seems to be using different net versions for Maui.

My advice is to build it locally & publish the nuget package it generates to a private nuget feed within your org.

The nuget package publishes automatically on build, it will be in the `bin/Release` folder.

Another way of using it is like you say, referencing the files locally with a `ProjectReference`. The benefit here would be you can make any changes / fixes locally but you would have to build locally aswell.

I hope this helps :)

**Comment by gsgou** [comment]
tks @Axemasta your project is helpful for migrating to MAUI even without support of some targets
