### ISSUE TITLE
Inconsistency in supported platforms / target frameworks

### ISSUE THREAD

**Issue by petroskin** [Axemasta/Maui.TouchEffect#4]
The README.md says that only the iOS and Android platforms are supported. However, looking at the code, Mac Catalyst and Windows are also listed in the target frameworks and supported platform versions (mainly looking at Directory.Build.props and the .csproj files).

Additionally, it would be good to have "net8.0" as a target framework in the Maui.TouchEffect project file, as this enables use of the library in unit test projects (having only net8.0 as a target framework).

**Comment by Axemasta** [comment]
Hey so when I say it only supports iOS & Android, there are only implementations for those platforms. I do have them listed as target frameworks, mainly because I still don't really trust maui's tooling with a single project approach not to get annoyed about no implementation on those platforms.

Because I've not put the library on nuget and I'm encouraging people to either reference the lib locally or build a nuget package and host within your organization / locally, you are free to modify the lib in anyway, including the `net8.0` target in your version.

I personally haven't tried unit testing my UI layer yet (since I used to use XF mock) so I didn't include the somewhat redundant framework target (redundant because our platform apps dont use it, only our tests).

**Comment by petroskin** [comment]
Thank you for taking the time.

As a note, I have added `net8.0` locally among the target frameworks, and the tests (ported from Xamarin Forms) run successfully.

**Comment by Axemasta** [comment]
I'm glad its working for you, I'm helping with the feature going into the MCT for real and hopefully the transition from this library to theirs is fairly painless!

I do know the name has changed to `TouchBehavior` and its no longer an attached effect, you need to add it to a control as opposed to just attaching what you need.
